### ISSUE TITLE
TODO: (get someone) Set up caching layer on project and to prepare for filtering phase

### ISSUE THREAD

**Issue by mikeybkats** [Sage-Bionetworks/amp-ad#14]
- Jay suggests building in caching layer (to optimize synapse api performance) 
- See about having Meredith prioritize the caching layer with the engineering team
- Jay suggests having Michael Lee develop the synapse react component to handle filtering and return of data
- Ljubo needs to make designs on the filtering so that development is informed about how to address those changes

**Comment by meredithslota** [comment]
Migrated to https://sagebionetworks.jira.com/browse/PORTALS-6.
