### ISSUE TITLE
Reference in-line widgets start at higher numbers within paragraphs in Studies that are further down the page

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/amp-ad#15]
Starting at The Mount Sinai Brain Bank (MSBB) Study, the reference in-line widget numbers within the paragraph don't start at 1, but at a higher number. When you get as far as the MayoLOADGWAS study, the paragraph reference numbers are 9 and 10:

<img width="1065" alt="paragraph" src="https://user-images.githubusercontent.com/12868382/44557950-497e9c00-a6f6-11e8-8a63-76813f177075.png">

But the Reference numbers at the end of the study have the correct numbers:
<img width="1036" alt="ref_at_end" src="https://user-images.githubusercontent.com/12868382/44557964-5c916c00-a6f6-11e8-850d-7a36f1918dda.png">

And the wikis of the Synapse folder for the study have the correct numbers rendering:
<img width="1395" alt="ref_numbers_in_synapse" src="https://user-images.githubusercontent.com/12868382/44558002-99f5f980-a6f6-11e8-8653-f241ee2a885d.png">

**Comment by mikeybkats** [comment]
this has been resolved. thank you @leem42

**Comment by ychae** [comment]
Thanks @leem42 ! 

The sequential order of the reference widgets has been resolved but it looks like that change resulted in another bug. I'll close this and open a new issue.
