### ISSUE TITLE
All widgets from Synapse wikis appear in a newline

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/amp-ad#23]
Anything that's a widget in a Synapse wiki appears on their own newline. So for buttons they appear like:
<img width="1018" alt="msbb_study_buttons_newline" src="https://user-images.githubusercontent.com/12868382/44885109-f9fb1b80-ac73-11e8-9b6f-6bb12d04fb52.png">

And the reference in-line widgets appear like:
<img width="1073" alt="ref_widgets_newline" src="https://user-images.githubusercontent.com/12868382/44885085-d3d57b80-ac73-11e8-897c-76af05aca4be.png">

**Comment by meredithslota** [comment]
Migrated to https://sagebionetworks.jira.com/browse/PORTALS-7.
