### ISSUE TITLE
Create content map

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/amp-ad#3]
Create a content map of what backend component matches to what front-end component.

**Comment by ychae** [comment]
First draft on paper completed. Need to create a digital version.

**Comment by ychae** [comment]
First pass of digital content map done, emailed to @annagree for review.

**Comment by meredithslota** [comment]
I think this is done, closing, not migrating to JIRA. Anything new that needs doing, let's open JIRA tickets! :)
