### ISSUE TITLE
Non-Reference Widget references don't have numbers

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/amp-ad#5]
Depending on how the references are referenced in the Synapse Wiki, the numbers sometimes disappears.

<img width="980" alt="ref_in_paragraph" src="https://user-images.githubusercontent.com/12868382/44482118-620a8b80-a5fc-11e8-8700-c2529949bd46.png">
<img width="919" alt="ref_non_widget" src="https://user-images.githubusercontent.com/12868382/44482122-6636a900-a5fc-11e8-9f73-39bd73413061.png">

Need to go into the backend and number the references in a way that show up in the front-end.

**Comment by jay-hodgson** [comment]
Should work once you update to the latest Synapse React Client.

**Comment by jay-hodgson** [comment]
@leem42 @mikeybkats

**Comment by leem42** [comment]
If the underlying markdown for those examples can get changed to be actual synapse references then they will render correctly, that would be the easiest fix I think.

**Comment by ychae** [comment]
Sounds good! I'll get those swapped over to widgets.

**Comment by ychae** [comment]
I've updated as many references into Synapse widgets that were feasible. The rest I've changed so that they render in a way that's easier to read on the site.
