### ISSUE TITLE
Twitter feed added to page

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/amp-ad#8]
Copying conversation from previous repo here:

Embed @AMPADPortal twitter handle into website

Why a twitter feed? The one in synapse takes a lot of space and is never really updated. What problem is this solving? Who will keep it active? Are users asking for this and if so why?

The @AMPADPortal <https://twitter.com/AMPADPortal>twitter is more actively
used than the Synapse feed, and was created by the request of the NIA. I
would like to embed it, not just a link. How about the home page under
'What's new'

Sure that works. Would it only show the 3 to 4 latest? I am trying to find good examples of people incorporating twitter feeds into their sites and can't find any yet.

Can we do as for Synapse:
https://www.synapse.org/ and make a vertical divide in the what's new section

We should take into consideration that the twitter feed has been strongly encouraged by the NIA

**Comment by meredithslota** [comment]
Let's not do this without design -- pulling into JIRA but assigning to @lbradic. https://sagebionetworks.jira.com/browse/PORTALS-2
