### ISSUE TITLE
Link to new portal from Synapse use requirements

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/amp-ad#9]
Remove data use requirements and add link from https://www.synapse.org/#!Synapse:syn2580853/wiki/409854 to (http://ampad-test.sagebase.org.s3-website-us-east-1.amazonaws.com/#/Resources/DataUseRequirements) once finalized

the page you are wanting to link to is at:
http://ampadportal.org/#/Resources/DataUseRequirements

**Comment by meredithslota** [comment]
Migrated to https://sagebionetworks.jira.com/browse/PORTALS-3.
